name: "Dockerize and Push"
description: "Auto-detect language and dockerize codebase"
inputs:
  image_tag:
    description: "Docker image tag"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
    - run: chmod +x scripts/entrypoint.sh
      shell: bash

    - name: Debug - print current directory
      shell: bash
      run: pwd

    - name: Debug - list scripts directory contents
      shell: bash
      run: ls -l ./scripts

    - name: Run Dockerize Script
      shell: bash
